[package]
name = "bt_iox"
version = "0.1.0"
edition = "2021"

[dependencies]
serialport = { version = "4.7.1", default-features =  false }
deku = "0.18.1"
time  = "0.3"
configparser = "3.0.5"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["default", "json"]}